### ISSUE TITLE
ParTI cannot be built without CUDA

### ISSUE THREAD

**Issue by ShadenSmith** [m13253/ParTI#2]
I have the following configuration in my `CMakeLists.txt`:
```
option(USE_CUDA "Use NVIDIA CUDA library" OFF)
option(USE_OpenBLAS "Use OpenBLAS library" OFF)
option(USE_MAGMA "Use MAGMA library" OFF)
option(USE_MKL "Use Intel MKL library" ON)
```

The configuration fails in the examples directory, though.
```
$ CC=icc CXX=icpc ./build.sh 
This script will do an out-of-tree build of ParTI into the 'build' directory.
-- The C compiler identification is Intel 16.0.3.20160415
-- The CXX compiler identification is Intel 16.0.3.20160415
-- Check for working C compiler: /export/scratch/shaden/local/intel/bin/icc
-- Check for working C compiler: /export/scratch/shaden/local/intel/bin/icc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /export/scratch/shaden/local/intel/bin/icpc
-- Check for working CXX compiler: /export/scratch/shaden/local/intel/bin/icpc -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Error at examples/CMakeLists.txt:7 (cuda_add_executable):
  Unknown CMake command "cuda_add_executable".
```

I believe the sources should be split into C and CUDA examples in order to select the correct `*_add_executable()` functions.

**Comment by m13253** [comment]
Thank you for your test and your report.

Our library is in early development stage, so we are sorry that we are not testing different configurations properly.

I have fixed your problem and now it compiles without CUDA.

Just a notice: This library is not stable and is not for production usage.
We are working hard on it and will probably release some new versions some months later.
More tests will be done, and more examples will be provided then.

**Comment by ShadenSmith** [comment]
Thanks for the quick fix! I'll report any other issues that I might find.

**Comment by fruitfly1026** [comment]
Thanks Shaden~
